
name: GitHub Actions 

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run workflow
        run: echo "Your push is running successfully!"

